In [85]:
def f(x):
    return x**3+2*x-2

def racine(N):
    import numpy as np
    intervalle = [0,0.5,1]
    compteur = 0
    
    while compteur < N:
        if f(intervalle[0])*f(intervalle[1]) < 0:
            intervalle = [intervalle[0], (intervalle[0] + intervalle[1])/2, intervalle[1]]
        else:
            intervalle = [intervalle[1], (intervalle[1] + intervalle[2])/2, intervalle[2]]
        compteur += 1
    return intervalle[1]

x = racine(10)
print(f(x))

0.0002992324298247695


In [88]:
import numpy as np

carre_de_3 = np.array([2,7,6,9,5,1,4,3,8]).reshape(3,3)
print(carre_de_3)

carre_de_4 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(carre_de_4)

def magique(carre):
    n = len(carre)
    Sn = (n*(n**2+1))/2
    
    somme_lignes = carre.sum(axis=1)
    print(somme_lignes)
    somme_colonnes = carre.sum(axis=0)
    somme_diag = carre.trace()
    somm

[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
